apiVersion: v1
kind: Service
metadata:
  name: gomailservice-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: go-mail-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: smtp
      port: 587
      targetPort: 587
      protocol: TCP
