apiVersion: v1
kind: Service
metadata:
  name: gomailservice-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: go-mail-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP