apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-mail-service.fullname" . }}-config
  labels:
    {{- include "go-mail-service.labels" . | nindent 4 }}
data:
  apiPort: "{{ .Values.service.port }}"
  defaultSenderMailAddress: "{{ .Values.defaultSenderMailAddress }}"
  defaultSenderName: "{{ .Values.defaultSenderName }}"
  isSendgridServiceEnabled: "{{ .Values.sendgridService.enabled }}"
  isNoopServiceEnabled: "{{ .Values.noopService.enabled }}"
  

