apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-mail-service.fullname" . }}
  labels:
    {{- include "go-mail-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go-mail-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.smtp.auth.required }}
        checksum/secret-smtp: {{ include (print $.Template.BasePath "/smtpsecret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.provider.mailjet.enabled }}
        checksum/secret-mailjet: {{ include (print $.Template.BasePath "/mailjetsecret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.provider.sendgrid.enabled }}
        checksum/secret-sendgrid: {{ include (print $.Template.BasePath "/sendgridsecret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "go-mail-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-mail-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
            - name: smtp
              containerPort: {{ .Values.smtp.port }}
              protocol: TCP
          env:
            - name: CONFIG_PATH
              value: /config/config.yaml
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.smtp.auth.required }}
            - name: smtp-secret
              mountPath: {{ .Values.smtp.auth.secret.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.provider.mailjet.enabled }}
            - name: mailjet-secret
              mountPath: {{ .Values.provider.mailjet.secret.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.provider.sendgrid.enabled }}
            - name: sendgrid-secret
              mountPath: {{ .Values.provider.sendgrid.secret.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "go-mail-service.fullname" . }}-config
        {{- if .Values.smtp.auth.required }}
        - name: smtp-secret
          secret:
            secretName: {{ .Values.smtp.auth.secret.name }}
        {{- end }}
        {{- if .Values.provider.mailjet.enabled }}
        - name: mailjet-secret
          secret:
            secretName: {{ .Values.provider.mailjet.secret.name }}
        {{- end }}
        {{- if .Values.provider.sendgrid.enabled }}
        - name: sendgrid-secret
          secret:
            secretName: {{ .Values.provider.sendgrid.secret.name }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
