{{- if .Values.provider.mailjet.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.provider.mailjet.secret.name }}"
  labels:
    {{- include "go-mail-service.labels" . | nindent 4 }}
stringData:
  apiKeyPublic: "{{ .Values.provider.mailjet.apiKeyPublic | default "" }}"
  apiKeyPrivate: "{{ .Values.provider.mailjet.apiKeyPrivate | default "" }}"
{{- end }}
