{{- if .Values.sendgridService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.sendgridService.secretName }}"
  labels:
    {{- include "go-mail-service.labels" . | nindent 4 }}
stringData:
  sendgridApiKey: "{{ .Values.sendgridService.apiKey }}"
{{- end }}