{{- if .Values.smtp.auth.required }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.smtp.auth.secret.name }}"
  labels:
    {{- include "go-mail-service.labels" . | nindent 4 }}
stringData:
  password: "{{ .Values.smtp.auth.password | default "" }}"
{{- end }}
